### PR TITLE
added codedeploy and elasticache message handling

### PR DESCRIPTION
**Pull request by knowroozi**
This module was super useful as a starting point for our org to get some aws sns messages into slack, but was missing some basic things that we needed (elasticache/codedeploy messaging). Not sure if you guys want to move in the direction of making this an all in one sns solution or not but that is something I'm planning on doing using this as a baseline. Figured I'd submit the PR for feedback and if you don't want to move in that direction, I'll just build on top of it in the fork for us.

I slso extracted the config to its own template so it wasn't as confusing on what i should or should not change in the base lambda handler

### CODE REVIEW

**Comment by creichert** [comment]
This looks really awesome. Give me a bit to test it and I don't see a problem merging this at all.

> Not sure if you guys want to move in the direction of making this an all in one sns solution or not 

We definitely want it to handle as many different kinds of notifications as possible. 

Very awesome!

**Comment by knowroozi** [comment]
This also probably will end up needing README changes because the config structure changed, but thanks for the merge! When I get around to other services we need this for, I'll submit some more PRs. 
We are also planning the ability to be able to mark different slack channels to get different notifications ... ie error snses to #error, deployment specific stuff to #deploy ... etc so each service could have its own slack target or icons or whatever... hence the services object in the config to stub out service specific variables/actions.

**Comment by creichert** [comment]
New version is uploaded to NPM: https://www.npmjs.com/package/lambda-cloudwatch-slack

I agree on the README and I don't mind doing it when I have some time today. Overall these improvements are incredible. https://twitter.com/AssertibleApp/status/763787324035469312

**Comment by kqdtran** [comment]
I found this app via r/aws. Needless to say, it's really awesome and is exactly what we need. What would be very useful is having the README updated (I don't know Node and was confused where the config in `index.js` was for example) and the explanation expanded (where would one find `AWS_ROLE` e.g.). Thanks so much!

**Comment by CodyReichert** [comment]
Hey, thanks @kqdtran for the reminder. I opened a new issue ( #2 ) so we can tackle it there.

**Pull request merged**
